-- =============================================================
-- NexusCX AI - Week 5 database schema (MVP core tables)
-- Database: PostgreSQL on Supabase
-- Owner: Prajita Shrestha
--
-- Builds the 9 core tables from the Week 4 ERD.
-- The other 8 ERD tables are planned for later sprints.
-- Changes from the ERD are listed in /docs/schema-changes.md
--
-- HOW TO RUN: Supabase dashboard -> SQL Editor -> New query
--             -> paste this whole file -> Run
--
-- WARNING: this script DROPS the 9 tables and rebuilds them.
-- =============================================================

-- Clean start (children first, because of foreign keys)
DROP TABLE IF EXISTS escalations, classifications, messages, conversations,
                     cases, knowledge_documents, ai_agents, customers, users CASCADE;

-- -------------------------------------------------------------
-- 1. users - everyone who logs in (all 4 roles)
-- -------------------------------------------------------------
CREATE TABLE users (
  user_id     UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  name        VARCHAR(100) NOT NULL,
  email       VARCHAR(254) NOT NULL,
  role        VARCHAR(20)  NOT NULL,
  status      VARCHAR(20)  NOT NULL DEFAULT 'active',
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT chk_users_role
    CHECK (role IN ('customer','support_agent','team_leader','admin')),
  CONSTRAINT chk_users_status
    CHECK (status IN ('active','inactive','suspended'))
);

-- -------------------------------------------------------------
-- 2. customers - extra profile details for customer users
--    One user has at most one customer profile (UNIQUE user_id)
-- -------------------------------------------------------------
CREATE TABLE customers (
  customer_id UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID         NOT NULL,
  phone       VARCHAR(20),
  address     VARCHAR(255),
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT uq_customers_user UNIQUE (user_id),
  CONSTRAINT fk_customers_user
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- -------------------------------------------------------------
-- 3. ai_agents - the specialist AI agents
-- -------------------------------------------------------------
CREATE TABLE ai_agents (
  agent_id    UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  name        VARCHAR(100) NOT NULL,
  type        VARCHAR(30)  NOT NULL,
  description VARCHAR(500),
  model_name  VARCHAR(100) NOT NULL,
  status      VARCHAR(20)  NOT NULL DEFAULT 'active',

  CONSTRAINT uq_ai_agents_name UNIQUE (name),
  CONSTRAINT chk_ai_agents_type
    CHECK (type IN ('orchestrator','technical_support','orders','billing','general')),
  CONSTRAINT chk_ai_agents_status
    CHECK (status IN ('active','inactive','draft'))
);

-- -------------------------------------------------------------
-- 4. knowledge_documents - approved content the AI may use (RAG)
--    Only status = 'approved' should be retrieved by agents
-- -------------------------------------------------------------
CREATE TABLE knowledge_documents (
  document_id UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  title       VARCHAR(200) NOT NULL,
  category    VARCHAR(50)  NOT NULL,
  content     TEXT         NOT NULL,
  status      VARCHAR(20)  NOT NULL DEFAULT 'draft',
  source      VARCHAR(255),
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT chk_knowledge_documents_status
    CHECK (status IN ('draft','approved','archived'))
);

-- -------------------------------------------------------------
-- 5. cases - the main support ticket
--    AI signals (intent, risk, etc.) live in classifications only
--    RESTRICT: a customer with cases cannot be deleted, so case
--    history is never lost. Deactivate the user instead.
-- -------------------------------------------------------------
--    case_number = the friendly number shown on screen (CX-10428)
--    assigned_agent_id = specialist AI agent handling the case;
--    NULL means it is waiting in the human queue
CREATE TABLE cases (
  case_id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  case_number       INTEGER      GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
  customer_id       UUID         NOT NULL,
  assigned_agent_id UUID,
  subject           VARCHAR(200) NOT NULL,
  status            VARCHAR(20)  NOT NULL DEFAULT 'ai_handling',
  priority          VARCHAR(10)  NOT NULL DEFAULT 'normal',
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
  closed_at         TIMESTAMPTZ,

  CONSTRAINT uq_cases_case_number UNIQUE (case_number),
  CONSTRAINT fk_cases_customer
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE RESTRICT,
  CONSTRAINT fk_cases_assigned_agent
    FOREIGN KEY (assigned_agent_id) REFERENCES ai_agents(agent_id) ON DELETE SET NULL,
  CONSTRAINT chk_cases_status
    CHECK (status IN ('ai_handling','waiting','escalated','resolved','closed')),
  CONSTRAINT chk_cases_priority
    CHECK (priority IN ('low','normal','medium','high')),
  CONSTRAINT chk_cases_dates
    CHECK (closed_at IS NULL OR closed_at >= created_at)
);

-- -------------------------------------------------------------
-- 6. conversations - a chat session belonging to a case
-- -------------------------------------------------------------
CREATE TABLE conversations (
  conversation_id UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id         UUID        NOT NULL,
  channel         VARCHAR(20) NOT NULL DEFAULT 'web_chat',
  started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at        TIMESTAMPTZ,

  CONSTRAINT fk_conversations_case
    FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE,
  CONSTRAINT chk_conversations_channel
    CHECK (channel IN ('web_chat','email','phone')),
  CONSTRAINT chk_conversations_dates
    CHECK (ended_at IS NULL OR ended_at >= started_at)
);

-- -------------------------------------------------------------
-- 7. messages - each message inside a conversation
--    sender_id has no FK: it can point to a user OR an AI agent,
--    depending on sender_type
-- -------------------------------------------------------------
CREATE TABLE messages (
  message_id      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID        NOT NULL,
  sender_type     VARCHAR(20) NOT NULL,
  sender_id       UUID,
  content         TEXT        NOT NULL,
  message_type    VARCHAR(20) NOT NULL DEFAULT 'text',
  "timestamp"     TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_messages_conversation
    FOREIGN KEY (conversation_id) REFERENCES conversations(conversation_id) ON DELETE CASCADE,
  CONSTRAINT chk_messages_sender_type
    CHECK (sender_type IN ('customer','ai','human_agent','system')),
  CONSTRAINT chk_messages_message_type
    CHECK (message_type IN ('text','attachment','system_note'))
);

-- -------------------------------------------------------------
-- 8. classifications - the AI's analysis of a case
--    confidence is a fixed decimal between 0 and 1 (never FLOAT)
-- -------------------------------------------------------------
CREATE TABLE classifications (
  classification_id UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id           UUID         NOT NULL,
  agent_id          UUID         NOT NULL,
  intent            VARCHAR(50)  NOT NULL,
  sentiment         VARCHAR(10)  NOT NULL,
  urgency           VARCHAR(10)  NOT NULL,
  risk              VARCHAR(10)  NOT NULL,
  language          VARCHAR(10)  NOT NULL DEFAULT 'en',
  confidence        NUMERIC(4,3) NOT NULL,
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT fk_classifications_case
    FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE,
  CONSTRAINT fk_classifications_agent
    FOREIGN KEY (agent_id) REFERENCES ai_agents(agent_id) ON DELETE RESTRICT,
  CONSTRAINT chk_classifications_sentiment
    CHECK (sentiment IN ('positive','neutral','negative','angry')),
  CONSTRAINT chk_classifications_urgency
    CHECK (urgency IN ('low','medium','high')),
  CONSTRAINT chk_classifications_risk
    CHECK (risk IN ('low','medium','high')),
  CONSTRAINT chk_classifications_confidence
    CHECK (confidence BETWEEN 0 AND 1)
);

-- -------------------------------------------------------------
-- 9. escalations - when a case is handed to a human
-- -------------------------------------------------------------
CREATE TABLE escalations (
  escalation_id  UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id        UUID         NOT NULL,
  reason         VARCHAR(255) NOT NULL,
  escalated_from VARCHAR(50)  NOT NULL,
  escalated_to   VARCHAR(50)  NOT NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  status         VARCHAR(20)  NOT NULL DEFAULT 'pending',

  CONSTRAINT fk_escalations_case
    FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE,
  CONSTRAINT chk_escalations_status
    CHECK (status IN ('pending','accepted','resolved'))
);

-- -------------------------------------------------------------
-- Indexes on foreign keys
-- (PostgreSQL does not create these automatically; MySQL does)
-- -------------------------------------------------------------
CREATE INDEX idx_cases_customer          ON cases(customer_id);
CREATE INDEX idx_cases_assigned_agent    ON cases(assigned_agent_id);
CREATE INDEX idx_conversations_case      ON conversations(case_id);
CREATE INDEX idx_messages_conversation   ON messages(conversation_id);
CREATE INDEX idx_classifications_case    ON classifications(case_id);
CREATE INDEX idx_classifications_agent   ON classifications(agent_id);
CREATE INDEX idx_escalations_case        ON escalations(case_id);

-- -------------------------------------------------------------
-- Security: Row Level Security (RLS)
-- Supabase exposes tables to the browser through an API.
-- RLS ON + no policy = nobody can read the table from the browser.
-- We then open ONLY what the Week 5 Cases page needs, read-only.
-- -------------------------------------------------------------
ALTER TABLE users               ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers           ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_agents           ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE cases               ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations       ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages            ENABLE ROW LEVEL SECURITY;
ALTER TABLE classifications     ENABLE ROW LEVEL SECURITY;
ALTER TABLE escalations         ENABLE ROW LEVEL SECURITY;

-- WEEK 5 DEMO ONLY: read-only access for the Cases page.
-- Data is fake. In Week 6, once login works, replace these with
-- role-based policies (e.g. only support agents can read cases).
CREATE POLICY demo_read_cases           ON cases           FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY demo_read_customers       ON customers       FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY demo_read_users           ON users           FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY demo_read_classifications ON classifications FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY demo_read_ai_agents       ON ai_agents       FOR SELECT TO anon, authenticated USING (true);

-- Make sure the browser API roles may SELECT these 5 tables
-- (RLS above still decides which rows they see)
GRANT SELECT ON cases, customers, users, classifications, ai_agents TO anon, authenticated;
