-- =============================================================
-- NexusCX AI - COMPLETE SUPABASE SETUP (tables + sample data)
-- PostgreSQL / Supabase only. Paste ALL of this into:
--   Supabase -> SQL Editor -> New query -> Run
-- If Supabase warns "destructive operation", click to confirm.
-- Safe to run again: it wipes and rebuilds the 9 tables.
-- The last result shows the row count of every table.
-- =============================================================

-- Clean start (children first, because of foreign keys)
DROP TABLE IF EXISTS escalations, classifications, messages, conversations,
                     cases, knowledge_documents, ai_agents, customers, users CASCADE;

-- -------------------------------------------------------------
-- 1. users - everyone who logs in (all 4 roles)
-- -------------------------------------------------------------
CREATE TABLE users (
  user_id     UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  name        VARCHAR(100) NOT NULL,
  email       VARCHAR(254) NOT NULL,
  role        VARCHAR(20)  NOT NULL,
  status      VARCHAR(20)  NOT NULL DEFAULT 'active',
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT chk_users_role
    CHECK (role IN ('customer','support_agent','team_leader','admin')),
  CONSTRAINT chk_users_status
    CHECK (status IN ('active','inactive','suspended'))
);

-- -------------------------------------------------------------
-- 2. customers - extra profile details for customer users
--    One user has at most one customer profile (UNIQUE user_id)
-- -------------------------------------------------------------
CREATE TABLE customers (
  customer_id UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID         NOT NULL,
  phone       VARCHAR(20),
  address     VARCHAR(255),
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT uq_customers_user UNIQUE (user_id),
  CONSTRAINT fk_customers_user
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- -------------------------------------------------------------
-- 3. ai_agents - the specialist AI agents
-- -------------------------------------------------------------
CREATE TABLE ai_agents (
  agent_id    UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  name        VARCHAR(100) NOT NULL,
  type        VARCHAR(30)  NOT NULL,
  description VARCHAR(500),
  model_name  VARCHAR(100) NOT NULL,
  status      VARCHAR(20)  NOT NULL DEFAULT 'active',

  CONSTRAINT uq_ai_agents_name UNIQUE (name),
  CONSTRAINT chk_ai_agents_type
    CHECK (type IN ('orchestrator','technical_support','orders','billing','general')),
  CONSTRAINT chk_ai_agents_status
    CHECK (status IN ('active','inactive','draft'))
);

-- -------------------------------------------------------------
-- 4. knowledge_documents - approved content the AI may use (RAG)
--    Only status = 'approved' should be retrieved by agents
-- -------------------------------------------------------------
CREATE TABLE knowledge_documents (
  document_id UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  title       VARCHAR(200) NOT NULL,
  category    VARCHAR(50)  NOT NULL,
  content     TEXT         NOT NULL,
  status      VARCHAR(20)  NOT NULL DEFAULT 'draft',
  source      VARCHAR(255),
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT chk_knowledge_documents_status
    CHECK (status IN ('draft','approved','archived'))
);

-- -------------------------------------------------------------
-- 5. cases - the main support ticket
--    AI signals (intent, risk, etc.) live in classifications only
--    RESTRICT: a customer with cases cannot be deleted, so case
--    history is never lost. Deactivate the user instead.
-- -------------------------------------------------------------
--    case_number = the friendly number shown on screen (CX-10428)
--    assigned_agent_id = specialist AI agent handling the case;
--    NULL means it is waiting in the human queue
CREATE TABLE cases (
  case_id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  case_number       INTEGER      GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
  customer_id       UUID         NOT NULL,
  assigned_agent_id UUID,
  subject           VARCHAR(200) NOT NULL,
  status            VARCHAR(20)  NOT NULL DEFAULT 'ai_handling',
  priority          VARCHAR(10)  NOT NULL DEFAULT 'normal',
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
  closed_at         TIMESTAMPTZ,

  CONSTRAINT uq_cases_case_number UNIQUE (case_number),
  CONSTRAINT fk_cases_customer
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE RESTRICT,
  CONSTRAINT fk_cases_assigned_agent
    FOREIGN KEY (assigned_agent_id) REFERENCES ai_agents(agent_id) ON DELETE SET NULL,
  CONSTRAINT chk_cases_status
    CHECK (status IN ('ai_handling','waiting','escalated','resolved','closed')),
  CONSTRAINT chk_cases_priority
    CHECK (priority IN ('low','normal','medium','high')),
  CONSTRAINT chk_cases_dates
    CHECK (closed_at IS NULL OR closed_at >= created_at)
);

-- -------------------------------------------------------------
-- 6. conversations - a chat session belonging to a case
-- -------------------------------------------------------------
CREATE TABLE conversations (
  conversation_id UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id         UUID        NOT NULL,
  channel         VARCHAR(20) NOT NULL DEFAULT 'web_chat',
  started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at        TIMESTAMPTZ,

  CONSTRAINT fk_conversations_case
    FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE,
  CONSTRAINT chk_conversations_channel
    CHECK (channel IN ('web_chat','email','phone')),
  CONSTRAINT chk_conversations_dates
    CHECK (ended_at IS NULL OR ended_at >= started_at)
);

-- -------------------------------------------------------------
-- 7. messages - each message inside a conversation
--    sender_id has no FK: it can point to a user OR an AI agent,
--    depending on sender_type
-- -------------------------------------------------------------
CREATE TABLE messages (
  message_id      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID        NOT NULL,
  sender_type     VARCHAR(20) NOT NULL,
  sender_id       UUID,
  content         TEXT        NOT NULL,
  message_type    VARCHAR(20) NOT NULL DEFAULT 'text',
  "timestamp"     TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_messages_conversation
    FOREIGN KEY (conversation_id) REFERENCES conversations(conversation_id) ON DELETE CASCADE,
  CONSTRAINT chk_messages_sender_type
    CHECK (sender_type IN ('customer','ai','human_agent','system')),
  CONSTRAINT chk_messages_message_type
    CHECK (message_type IN ('text','attachment','system_note'))
);

-- -------------------------------------------------------------
-- 8. classifications - the AI's analysis of a case
--    confidence is a fixed decimal between 0 and 1 (never FLOAT)
-- -------------------------------------------------------------
CREATE TABLE classifications (
  classification_id UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id           UUID         NOT NULL,
  agent_id          UUID         NOT NULL,
  intent            VARCHAR(50)  NOT NULL,
  sentiment         VARCHAR(10)  NOT NULL,
  urgency           VARCHAR(10)  NOT NULL,
  risk              VARCHAR(10)  NOT NULL,
  language          VARCHAR(10)  NOT NULL DEFAULT 'en',
  confidence        NUMERIC(4,3) NOT NULL,
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT fk_classifications_case
    FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE,
  CONSTRAINT fk_classifications_agent
    FOREIGN KEY (agent_id) REFERENCES ai_agents(agent_id) ON DELETE RESTRICT,
  CONSTRAINT chk_classifications_sentiment
    CHECK (sentiment IN ('positive','neutral','negative','angry')),
  CONSTRAINT chk_classifications_urgency
    CHECK (urgency IN ('low','medium','high')),
  CONSTRAINT chk_classifications_risk
    CHECK (risk IN ('low','medium','high')),
  CONSTRAINT chk_classifications_confidence
    CHECK (confidence BETWEEN 0 AND 1)
);

-- -------------------------------------------------------------
-- 9. escalations - when a case is handed to a human
-- -------------------------------------------------------------
CREATE TABLE escalations (
  escalation_id  UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id        UUID         NOT NULL,
  reason         VARCHAR(255) NOT NULL,
  escalated_from VARCHAR(50)  NOT NULL,
  escalated_to   VARCHAR(50)  NOT NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  status         VARCHAR(20)  NOT NULL DEFAULT 'pending',

  CONSTRAINT fk_escalations_case
    FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE,
  CONSTRAINT chk_escalations_status
    CHECK (status IN ('pending','accepted','resolved'))
);

-- -------------------------------------------------------------
-- Indexes on foreign keys
-- (PostgreSQL does not create these automatically; MySQL does)
-- -------------------------------------------------------------
CREATE INDEX idx_cases_customer          ON cases(customer_id);
CREATE INDEX idx_cases_assigned_agent    ON cases(assigned_agent_id);
CREATE INDEX idx_conversations_case      ON conversations(case_id);
CREATE INDEX idx_messages_conversation   ON messages(conversation_id);
CREATE INDEX idx_classifications_case    ON classifications(case_id);
CREATE INDEX idx_classifications_agent   ON classifications(agent_id);
CREATE INDEX idx_escalations_case        ON escalations(case_id);

-- -------------------------------------------------------------
-- Security: Row Level Security (RLS)
-- Supabase exposes tables to the browser through an API.
-- RLS ON + no policy = nobody can read the table from the browser.
-- We then open ONLY what the Week 5 Cases page needs, read-only.
-- -------------------------------------------------------------
ALTER TABLE users               ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers           ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_agents           ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE cases               ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations       ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages            ENABLE ROW LEVEL SECURITY;
ALTER TABLE classifications     ENABLE ROW LEVEL SECURITY;
ALTER TABLE escalations         ENABLE ROW LEVEL SECURITY;

-- WEEK 5 DEMO ONLY: read-only access for the Cases page.
-- Data is fake. In Week 6, once login works, replace these with
-- role-based policies (e.g. only support agents can read cases).
CREATE POLICY demo_read_cases           ON cases           FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY demo_read_customers       ON customers       FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY demo_read_users           ON users           FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY demo_read_classifications ON classifications FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY demo_read_ai_agents       ON ai_agents       FOR SELECT TO anon, authenticated USING (true);

-- Make sure the browser API roles may SELECT these 5 tables
-- (RLS above still decides which rows they see)
GRANT SELECT ON cases, customers, users, classifications, ai_agents TO anon, authenticated;


-- -------------------------------------------------------------
-- SAMPLE DATA
-- -------------------------------------------------------------
-- 1. users (7 customers + 4 staff, one for each staff role)
-- -------------------------------------------------------------
INSERT INTO users (user_id, name, email, role, status) VALUES
('11111111-0000-0000-0000-000000000001', 'Sarah Chen',     'sarah.chen@example.test',     'customer',      'active'),
('11111111-0000-0000-0000-000000000002', 'James Wilson',   'james.wilson@example.test',   'customer',      'active'),
('11111111-0000-0000-0000-000000000003', 'Maya Patel',     'maya.patel@example.test',     'customer',      'active'),
('11111111-0000-0000-0000-000000000004', 'David Kim',      'david.kim@example.test',      'customer',      'active'),
('11111111-0000-0000-0000-000000000005', 'Emma Rodriguez', 'emma.rodriguez@example.test', 'customer',      'active'),
('11111111-0000-0000-0000-000000000006', 'Thomas Lee',     'thomas.lee@example.test',     'customer',      'active'),
('11111111-0000-0000-0000-000000000007', 'Priya Sharma',   'priya.sharma@example.test',   'customer',      'inactive'),
('11111111-0000-0000-0000-000000000011', 'Alex Morgan',    'alex.morgan@nexuscx.test',    'support_agent', 'active'),
('11111111-0000-0000-0000-000000000012', 'Jordan Blake',   'jordan.blake@nexuscx.test',   'support_agent', 'active'),
('11111111-0000-0000-0000-000000000013', 'Ethan Walker',   'ethan.walker@nexuscx.test',   'team_leader',   'active'),
('11111111-0000-0000-0000-000000000014', 'Sophie Martin',  'sophie.martin@nexuscx.test',  'admin',         'active');

-- -------------------------------------------------------------
-- 2. customers (one profile for each customer user)
-- -------------------------------------------------------------
INSERT INTO customers (customer_id, user_id, phone, address) VALUES
('22222222-0000-0000-0000-000000000001', '11111111-0000-0000-0000-000000000001', '0400 000 001', '12 Example St, Sydney NSW 2000'),
('22222222-0000-0000-0000-000000000002', '11111111-0000-0000-0000-000000000002', '0400 000 002', '45 Sample Rd, Parramatta NSW 2150'),
('22222222-0000-0000-0000-000000000003', '11111111-0000-0000-0000-000000000003', NULL,           '8 Test Ave, Melbourne VIC 3000'),
('22222222-0000-0000-0000-000000000004', '11111111-0000-0000-0000-000000000004', '0400 000 004', NULL),
('22222222-0000-0000-0000-000000000005', '11111111-0000-0000-0000-000000000005', '0400 000 005', '3 Demo Lane, Brisbane QLD 4000'),
('22222222-0000-0000-0000-000000000006', '11111111-0000-0000-0000-000000000006', '0400 000 006', '27 Mock Pde, Perth WA 6000'),
('22222222-0000-0000-0000-000000000007', '11111111-0000-0000-0000-000000000007', NULL,           NULL);

-- -------------------------------------------------------------
-- 3. ai_agents (orchestrator + 3 specialists, as in the prototype)
-- -------------------------------------------------------------
INSERT INTO ai_agents (agent_id, name, type, description, model_name, status) VALUES
('33333333-0000-0000-0000-000000000001', 'AI Orchestrator', 'orchestrator',      'Classifies each enquiry and routes it to the right specialist agent.', 'gpt-4o-mini', 'active'),
('33333333-0000-0000-0000-000000000002', 'Technical Agent', 'technical_support', 'Handles login problems, app errors and how-to questions.',            'gpt-4o-mini', 'active'),
('33333333-0000-0000-0000-000000000003', 'Order Agent',     'orders',            'Handles order status, delivery and returns questions.',               'gpt-4o-mini', 'active'),
('33333333-0000-0000-0000-000000000004', 'Billing Agent',   'billing',           'Explains invoices and charges. Refunds are escalated to a human.',    'gpt-4o-mini', 'active');

-- -------------------------------------------------------------
-- 4. knowledge_documents (6 approved, 1 draft)
--    The draft must NOT be used by the AI - good to show in demo
-- -------------------------------------------------------------
INSERT INTO knowledge_documents (document_id, title, category, content, status, source) VALUES
('44444444-0000-0000-0000-000000000001', 'Billing Policy v4.2', 'billing',
 'Customers are billed monthly on their sign-up date. Invoices list each charge, GST and the total, and are available under Account > Billing.',
 'approved', 'Finance team'),
('44444444-0000-0000-0000-000000000002', 'Refund Procedure v2.1', 'billing',
 'Refunds must be approved by a human staff member. The AI assistant can explain the process but cannot issue a refund.',
 'approved', 'Finance team'),
('44444444-0000-0000-0000-000000000003', 'Payment Terms v3.0', 'billing',
 'Payment is due within 14 days of the invoice date. Duplicate charges are reversed within 5 business days once confirmed.',
 'approved', 'Finance team'),
('44444444-0000-0000-0000-000000000004', 'Delivery Times', 'orders',
 'Standard delivery takes 3-5 business days in metro areas and 5-8 business days in regional areas.',
 'approved', 'Shipping Policy 2026'),
('44444444-0000-0000-0000-000000000005', 'Missing or Damaged Items', 'orders',
 'If an item is missing or damaged, the customer can report it within 7 days of delivery for a replacement.',
 'approved', 'Returns Policy 2026'),
('44444444-0000-0000-0000-000000000006', 'Password Reset Guide', 'technical',
 'Click "Forgot password" on the login page. A reset link is emailed within 5 minutes and expires after 1 hour.',
 'approved', 'Help Centre'),
('44444444-0000-0000-0000-000000000007', 'New Loyalty Program (draft)', 'general',
 'Draft content - not yet approved by the administrator.',
 'draft', 'Marketing team');

-- -------------------------------------------------------------
-- 5. cases (the 7 cases from the prototype's Case Queue)
--    assigned_agent_id NULL = waiting in the Human Queue
-- -------------------------------------------------------------
INSERT INTO cases (case_id, case_number, customer_id, assigned_agent_id, subject, status, priority, created_at, closed_at) VALUES
('55555555-0000-0000-0000-000000000001', 10422, '22222222-0000-0000-0000-000000000007', '33333333-0000-0000-0000-000000000004', 'Upgrade plan enquiry',           'resolved',    'low',    '2026-10-07 08:40:00+11', '2026-10-07 08:52:00+11'),
('55555555-0000-0000-0000-000000000002', 10423, '22222222-0000-0000-0000-000000000006', NULL,                                   'Missing item in order',          'escalated',   'high',   '2026-10-07 08:55:00+11', NULL),
('55555555-0000-0000-0000-000000000003', 10424, '22222222-0000-0000-0000-000000000005', '33333333-0000-0000-0000-000000000002', 'Password reset not working',     'waiting',     'normal', '2026-10-07 09:10:00+11', NULL),
('55555555-0000-0000-0000-000000000004', 10425, '22222222-0000-0000-0000-000000000004', '33333333-0000-0000-0000-000000000004', 'Invoice explanation Q3',         'ai_handling', 'normal', '2026-10-07 09:20:00+11', NULL),
('55555555-0000-0000-0000-000000000005', 10426, '22222222-0000-0000-0000-000000000003', '33333333-0000-0000-0000-000000000002', 'AUTH-403 Login Error',           'escalated',   'high',   '2026-10-07 09:28:00+11', NULL),
('55555555-0000-0000-0000-000000000006', 10427, '22222222-0000-0000-0000-000000000002', '33333333-0000-0000-0000-000000000003', 'Order #ORD-88219 Not Arrived',   'ai_handling', 'medium', '2026-10-07 09:35:00+11', NULL),
('55555555-0000-0000-0000-000000000007', 10428, '22222222-0000-0000-0000-000000000001', NULL,                                   'Duplicate Subscription Payment', 'escalated',   'high',   '2026-10-07 09:41:00+11', NULL);

-- New cases continue from CX-10429
SELECT setval(pg_get_serial_sequence('cases', 'case_number'), (SELECT max(case_number) FROM cases));

-- -------------------------------------------------------------
-- 6. conversations (one web chat per case)
-- -------------------------------------------------------------
INSERT INTO conversations (conversation_id, case_id, channel, started_at, ended_at) VALUES
('66666666-0000-0000-0000-000000000001', '55555555-0000-0000-0000-000000000001', 'web_chat', '2026-10-07 08:40:00+11', '2026-10-07 08:52:00+11'),
('66666666-0000-0000-0000-000000000002', '55555555-0000-0000-0000-000000000002', 'web_chat', '2026-10-07 08:55:00+11', NULL),
('66666666-0000-0000-0000-000000000003', '55555555-0000-0000-0000-000000000003', 'web_chat', '2026-10-07 09:10:00+11', NULL),
('66666666-0000-0000-0000-000000000004', '55555555-0000-0000-0000-000000000004', 'email',    '2026-10-07 09:20:00+11', NULL),
('66666666-0000-0000-0000-000000000005', '55555555-0000-0000-0000-000000000005', 'web_chat', '2026-10-07 09:28:00+11', NULL),
('66666666-0000-0000-0000-000000000006', '55555555-0000-0000-0000-000000000006', 'web_chat', '2026-10-07 09:35:00+11', NULL),
('66666666-0000-0000-0000-000000000007', '55555555-0000-0000-0000-000000000007', 'web_chat', '2026-10-07 09:41:00+11', NULL);

-- -------------------------------------------------------------
-- 7. messages
-- -------------------------------------------------------------
INSERT INTO messages (message_id, conversation_id, sender_type, sender_id, content, message_type, "timestamp") VALUES
-- CX-10422 Upgrade plan - solved by AI
('77777777-0000-0000-0000-000000000001', '66666666-0000-0000-0000-000000000001', 'customer', '11111111-0000-0000-0000-000000000007', 'How do I upgrade to the Professional plan?', 'text', '2026-10-07 08:40:00+11'),
('77777777-0000-0000-0000-000000000002', '66666666-0000-0000-0000-000000000001', 'ai',       '33333333-0000-0000-0000-000000000004', 'You can upgrade any time under Account > Billing > Change plan. The new price applies from your next billing date.', 'text', '2026-10-07 08:40:20+11'),
-- CX-10423 Missing item - escalated
('77777777-0000-0000-0000-000000000003', '66666666-0000-0000-0000-000000000002', 'customer', '11111111-0000-0000-0000-000000000006', 'My order arrived but one item is missing. I paid for it!', 'text', '2026-10-07 08:55:00+11'),
('77777777-0000-0000-0000-000000000004', '66666666-0000-0000-0000-000000000002', 'system',   NULL, 'Replacement request needs staff approval. Case escalated to Human Queue.', 'system_note', '2026-10-07 08:55:15+11'),
-- CX-10424 Password reset - waiting for customer
('77777777-0000-0000-0000-000000000005', '66666666-0000-0000-0000-000000000003', 'customer', '11111111-0000-0000-0000-000000000005', 'The password reset link is not working.', 'text', '2026-10-07 09:10:00+11'),
('77777777-0000-0000-0000-000000000006', '66666666-0000-0000-0000-000000000003', 'ai',       '33333333-0000-0000-0000-000000000002', 'Reset links expire after 1 hour. I have sent a new link - can you try it and let me know?', 'text', '2026-10-07 09:10:20+11'),
-- CX-10425 Invoice question - AI handling
('77777777-0000-0000-0000-000000000007', '66666666-0000-0000-0000-000000000004', 'customer', '11111111-0000-0000-0000-000000000004', 'Can you explain the charges on my Q3 invoice?', 'text', '2026-10-07 09:20:00+11'),
('77777777-0000-0000-0000-000000000008', '66666666-0000-0000-0000-000000000004', 'ai',       '33333333-0000-0000-0000-000000000004', 'Your invoice lists each monthly charge plus GST. Would you like me to go through each line?', 'text', '2026-10-07 09:20:25+11'),
-- CX-10426 Login error - escalated
('77777777-0000-0000-0000-000000000009', '66666666-0000-0000-0000-000000000005', 'customer', '11111111-0000-0000-0000-000000000003', 'I keep getting AUTH-403 when I log in. I cannot access anything.', 'text', '2026-10-07 09:28:00+11'),
('77777777-0000-0000-0000-000000000010', '66666666-0000-0000-0000-000000000005', 'system',   NULL, 'Account access issue with high risk. Case escalated to support agent.', 'system_note', '2026-10-07 09:28:20+11'),
-- CX-10427 Order not arrived - AI handling
('77777777-0000-0000-0000-000000000011', '66666666-0000-0000-0000-000000000006', 'customer', '11111111-0000-0000-0000-000000000002', 'Order #ORD-88219 has not arrived yet.', 'text', '2026-10-07 09:35:00+11'),
('77777777-0000-0000-0000-000000000012', '66666666-0000-0000-0000-000000000006', 'ai',       '33333333-0000-0000-0000-000000000003', 'Standard delivery to metro areas takes 3-5 business days. Your order is in transit and due tomorrow.', 'text', '2026-10-07 09:35:20+11'),
-- CX-10428 Duplicate payment - escalated (refund = restricted action)
('77777777-0000-0000-0000-000000000013', '66666666-0000-0000-0000-000000000007', 'customer', '11111111-0000-0000-0000-000000000001', 'Hi, I was charged twice for my subscription this month. I need the extra payment refunded.', 'text', '2026-10-07 09:41:00+11'),
('77777777-0000-0000-0000-000000000014', '66666666-0000-0000-0000-000000000007', 'ai',       '33333333-0000-0000-0000-000000000004', 'I am sorry about this. Refunds need approval from our staff, so I have passed your case to a support agent.', 'text', '2026-10-07 09:41:25+11'),
('77777777-0000-0000-0000-000000000015', '66666666-0000-0000-0000-000000000007', 'system',   NULL, 'Refund is a restricted action. Case escalated to Human Queue.', 'system_note', '2026-10-07 09:41:26+11');

-- -------------------------------------------------------------
-- 8. classifications (one per case, made by the orchestrator)
-- -------------------------------------------------------------
INSERT INTO classifications (classification_id, case_id, agent_id, intent, sentiment, urgency, risk, language, confidence, created_at) VALUES
('88888888-0000-0000-0000-000000000001', '55555555-0000-0000-0000-000000000001', '33333333-0000-0000-0000-000000000001', 'billing',   'positive', 'low',    'low',    'en', 0.970, '2026-10-07 08:40:05+11'),
('88888888-0000-0000-0000-000000000002', '55555555-0000-0000-0000-000000000002', '33333333-0000-0000-0000-000000000001', 'order',     'negative', 'high',   'medium', 'en', 0.890, '2026-10-07 08:55:05+11'),
('88888888-0000-0000-0000-000000000003', '55555555-0000-0000-0000-000000000003', '33333333-0000-0000-0000-000000000001', 'technical', 'neutral',  'medium', 'low',    'en', 0.930, '2026-10-07 09:10:05+11'),
('88888888-0000-0000-0000-000000000004', '55555555-0000-0000-0000-000000000004', '33333333-0000-0000-0000-000000000001', 'billing',   'neutral',  'low',    'low',    'en', 0.910, '2026-10-07 09:20:05+11'),
('88888888-0000-0000-0000-000000000005', '55555555-0000-0000-0000-000000000005', '33333333-0000-0000-0000-000000000001', 'technical', 'negative', 'high',   'high',   'en', 0.620, '2026-10-07 09:28:05+11'),
('88888888-0000-0000-0000-000000000006', '55555555-0000-0000-0000-000000000006', '33333333-0000-0000-0000-000000000001', 'order',     'neutral',  'medium', 'low',    'en', 0.940, '2026-10-07 09:35:05+11'),
('88888888-0000-0000-0000-000000000007', '55555555-0000-0000-0000-000000000007', '33333333-0000-0000-0000-000000000001', 'billing',   'angry',    'high',   'high',   'en', 0.960, '2026-10-07 09:41:05+11');

-- -------------------------------------------------------------
-- 9. escalations (the three escalated cases)
-- -------------------------------------------------------------
INSERT INTO escalations (escalation_id, case_id, reason, escalated_from, escalated_to, created_at, status) VALUES
('99999999-0000-0000-0000-000000000001', '55555555-0000-0000-0000-000000000002', 'Replacement request - restricted action needs staff approval', 'order_agent',   'human_queue',   '2026-10-07 08:55:15+11', 'pending'),
('99999999-0000-0000-0000-000000000002', '55555555-0000-0000-0000-000000000005', 'High risk account access issue, confidence 0.62',            'orchestrator',  'support_agent', '2026-10-07 09:28:20+11', 'accepted'),
('99999999-0000-0000-0000-000000000003', '55555555-0000-0000-0000-000000000007', 'Refund request - restricted action needs human approval',     'billing_agent', 'human_queue',   '2026-10-07 09:41:26+11', 'pending');

-- -------------------------------------------------------------
-- CHECK: you should see 9 rows. cases = 7.
-- -------------------------------------------------------------
SELECT 'users' AS table_name, count(*) AS row_count FROM users
UNION ALL SELECT 'customers', count(*) FROM customers
UNION ALL SELECT 'ai_agents', count(*) FROM ai_agents
UNION ALL SELECT 'knowledge_documents', count(*) FROM knowledge_documents
UNION ALL SELECT 'cases', count(*) FROM cases
UNION ALL SELECT 'conversations', count(*) FROM conversations
UNION ALL SELECT 'messages', count(*) FROM messages
UNION ALL SELECT 'classifications', count(*) FROM classifications
UNION ALL SELECT 'escalations', count(*) FROM escalations;
